### ISSUE TITLE
Update height of provider notes to fill screen vertically

### ISSUE THREAD

**Issue by TipTom** [Civicom/conjure_ottehr#20]
For the div class below, update the css so the height is "60vh"

<div class="MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-feqhe6"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined css-1936n3y" data-shrink="true" for=":r11:" id=":r11:-label">Provider Notes</label>

May also need to set height over other parent div classes to 100%

@michaelmunson-civi can provide quick guidance if needed on how to do

**Comment by Charles92011** [comment]
It has a hard-coded height based on "rows". Currently it's set to 12, which fills my small monitor, but winds up short on my big monitor.
I set it to twenty. Is it ok if it goes beyond the bottom of the screen?
